name: makerequest
description: Flutter is Google’s UI toolkit for building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase. This template is created by nhancv.
version: 2.0.0+202106001


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  meta: ^1.3.0
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0


  provider: ^5.0.0
  logger: ^1.0.0
  tuple: ^2.0.0
  dio: ^4.0.0
  email_validator: ^2.0.1

  simple_animations: ^3.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.22.0
  cloud_firestore: ^2.5.3
  firebase_core: ^1.2.0
  firebase_crashlytics: ^2.2.1
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.1
  flutter_facebook_auth: ^3.5.2
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.1
  image_picker: ^0.8.4+2
  equatable: ^2.0.3
  firebase_storage: ^10.0.4
  cached_network_image: ^3.1.0
  image_cropper: ^1.4.1
  photo_view: ^0.12.0
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  firebase_messaging: 10.0.1




flutter_intl:
  enabled: true

dev_dependencies:
  build_runner: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: any
  mockito: any
  test: any
  flutter_launcher_icons: any

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/base/icons/app_icon_ios.png"
  image_path_android: "assets/base/icons/app_icon_ad.png"
  adaptive_icon_background: "assets/base/icons/adaptive_icon_background.png" # for Android 8.0+ devices
  adaptive_icon_foreground: "assets/base/icons/adaptive_icon_foreground.png" # for Android 8.0+ devices
# To Generate icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/base/icons/
    - assets/base/fonts/
    - assets/app/icons/
    - assets/app/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/base/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/base/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/base/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/base/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/base/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/base/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Lato
      fonts:
        - asset: assets/app/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/app/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/app/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/app/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/app/fonts/Lato/Lato-BlackItalic.ttf
          style: italic
          weight: 900

